"""empty message

Revision ID: 15a2d076584e
Revises: 0710f4b5ab1e
Create Date: 2021-04-22 01:05:37.310571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a2d076584e'
down_revision = '0710f4b5ab1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('File',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('fileType', sa.String(length=100), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('assignmentId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('userType', sa.String(length=100), nullable=True),
    sa.Column('hasAccess', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Instructor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message', sa.String(length=100), nullable=False),
    sa.Column('senderId', sa.Integer(), nullable=True),
    sa.Column('recipientId', sa.Integer(), nullable=True),
    sa.Column('dateTime', sa.DateTime(), nullable=False),
    sa.Column('isRead', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['recipientId'], ['User.id'], ondelete='set null'),
    sa.ForeignKeyConstraint(['senderId'], ['User.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('instructorId', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=10000), nullable=True),
    sa.Column('semester', sa.String(length=100), nullable=True),
    sa.Column('organization', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['instructorId'], ['Instructor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('adminId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['adminId'], ['Admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('subject', sa.String(length=1000), nullable=True),
    sa.Column('dateTime', sa.DateTime(), nullable=False),
    sa.Column('courseId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['courseId'], ['Course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('courseId', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('fileLoc', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['courseId'], ['Course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('StudentCourses',
    sa.Column('courseId', sa.Integer(), nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['courseId'], ['Course.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['studentId'], ['Student.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('courseId', 'studentId')
    )
    op.create_table('UserOrganizations',
    sa.Column('organizationId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizationId'], ['Organization.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('organizationId', 'userId')
    )
    op.create_table('Assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('courseId', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('moduleId', sa.Integer(), nullable=False),
    sa.Column('dueDate', sa.String(length=1000), nullable=True),
    sa.Column('fileLoc', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['courseId'], ['Course.id'], ),
    sa.ForeignKeyConstraint(['moduleId'], ['Module.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('AssignmentGrades',
    sa.Column('assignmentId', sa.Integer(), nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('fileLoc', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignmentId'], ['Assignment.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['studentId'], ['Student.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('assignmentId', 'studentId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AssignmentGrades')
    op.drop_table('Assignment')
    op.drop_table('UserOrganizations')
    op.drop_table('StudentCourses')
    op.drop_table('Module')
    op.drop_table('Announcement')
    op.drop_table('Organization')
    op.drop_table('Course')
    op.drop_table('Student')
    op.drop_table('Message')
    op.drop_table('Instructor')
    op.drop_table('Admin')
    op.drop_table('User')
    op.drop_table('File')
    # ### end Alembic commands ###
