"""empty message

Revision ID: 2b6219e745a6
Revises: 3ab68de76aab
Create Date: 2021-04-19 00:20:57.199608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b6219e745a6'
down_revision = '3ab68de76aab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AssignmentGrades', 'fileLoc')
    op.add_column('File', sa.Column('userId', sa.Integer(), nullable=True))
    op.alter_column('File', 'assignmentId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('File', 'moduleId',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('File', 'moduleId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('File', 'assignmentId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('File', 'userId')
    op.add_column('AssignmentGrades', sa.Column('fileLoc', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
