"""empty message

Revision ID: 55f07471b2d0
Revises: 8c9b397369dd
Create Date: 2021-04-20 21:37:15.488269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f07471b2d0'
down_revision = '8c9b397369dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Assignment', sa.Column('points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Assignment', 'points')
    # ### end Alembic commands ###
