"""empty message

Revision ID: 6e811e589856
Revises: da8e93022732
Create Date: 2021-04-19 00:32:05.134967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e811e589856'
down_revision = 'da8e93022732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AssignmentGrades', sa.Column('fileLoc', sa.Integer(), nullable=True))
    op.drop_constraint('File_moduleId_fkey', 'File', type_='foreignkey')
    op.drop_constraint('File_assignmentId_fkey', 'File', type_='foreignkey')
    op.drop_column('File', 'moduleId')
    op.drop_column('File', 'assignmentId')
    op.add_column('Module', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('Module', sa.Column('fileLoc', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Module', 'fileLoc')
    op.drop_column('Module', 'description')
    op.add_column('File', sa.Column('assignmentId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('File', sa.Column('moduleId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('File_assignmentId_fkey', 'File', 'Assignment', ['assignmentId'], ['id'])
    op.create_foreign_key('File_moduleId_fkey', 'File', 'Module', ['moduleId'], ['id'])
    op.drop_column('AssignmentGrades', 'fileLoc')
    # ### end Alembic commands ###
